// <auto-generated />
using System;
using ERP.Infrastructur;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP.API.Migrations
{
    [DbContext(typeof(ERPContext))]
    [Migration("20200622103647_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP.Domain.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addition")
                        .HasColumnName("addition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Addition2")
                        .HasColumnName("addition2")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("CompanyTypeId")
                        .HasColumnName("fk_address_company_type")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnName("fk_address_country")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnName("fax")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LogoId")
                        .HasColumnName("fk_logo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)")
                        .HasMaxLength(1000);

                    b.Property<Guid?>("ParentId")
                        .HasColumnName("fk_parent_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PostCode")
                        .HasColumnName("postcode")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Street")
                        .HasColumnName("street")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnName("timezone")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("VatId")
                        .HasColumnName("vat_id_no")
                        .HasColumnType("varchar(max)");

                    b.HasKey("CompanyId");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LogoId");

                    b.HasIndex("ParentId");

                    b.ToTable("Company","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.CompanyPersonRelation", b =>
                {
                    b.Property<Guid>("CompanyPersonRelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnName("fk_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyPersonId")
                        .HasColumnName("fk_person")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("CompanyPersonRelationId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyPersonId");

                    b.ToTable("CompanyPersonRelation","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Article", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnName("fk_group")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnName("fk_type")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("Dim2")
                        .HasColumnName("dim_2")
                        .HasColumnType("int");

                    b.Property<int>("Dim3")
                        .HasColumnName("dim_3")
                        .HasColumnType("int");

                    b.Property<int>("Dim4")
                        .HasColumnName("dim_4")
                        .HasColumnType("int");

                    b.Property<int>("DimArea")
                        .HasColumnName("dim_area")
                        .HasColumnType("int");

                    b.Property<int>("DimLength")
                        .HasColumnName("dim_length")
                        .HasColumnType("int");

                    b.Property<string>("DinNorm1")
                        .HasColumnName("din_norm1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinNorm2")
                        .HasColumnName("din_norm2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingNumber")
                        .HasColumnName("drawing_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBatch")
                        .HasColumnName("is_batch")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCasting")
                        .HasColumnName("is_casting")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnName("is_discontinued")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscountEnabled")
                        .HasColumnName("is_discount_enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisposition")
                        .HasColumnName("is_disposition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultistock")
                        .HasColumnName("is_multistock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProvisionEnabled")
                        .HasColumnName("is_provision_enabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemNumber")
                        .HasColumnName("item_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaterialType")
                        .HasColumnName("material_type")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("ScaleUnitQty")
                        .HasColumnName("scale_unit_qty")
                        .HasColumnType("int");

                    b.Property<int>("ScaleUnitType")
                        .HasColumnName("scale_unit_type")
                        .HasColumnType("int");

                    b.Property<decimal>("SpecificWeight")
                        .HasColumnName("specific_weight")
                        .HasColumnType("decimal (38,20)");

                    b.Property<int>("UnitStock")
                        .HasColumnName("unit_stock")
                        .HasColumnType("int");

                    b.Property<int>("UnitStockIn")
                        .HasColumnName("unit_stock_in")
                        .HasColumnType("int");

                    b.Property<int>("UnitStockOut")
                        .HasColumnName("unit_stock_out")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.HasIndex("Id");

                    b.HasIndex("Id");

                    b.ToTable("article","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("article_group","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleInventory", b =>
                {
                    b.Property<Guid>("ArticleInventoryId")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnName("fk_article")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnName("fk_place")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.HasKey("ArticleInventoryId");

                    b.HasIndex("Id");

                    b.ToTable("article_inventory","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnName("fk_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumQty")
                        .HasColumnName("minimum_qty")
                        .HasColumnType("decimal (38,20)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OpoQty")
                        .HasColumnName("opo_qty")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("ReservedQty")
                        .HasColumnName("reserved_qty")
                        .HasColumnType("decimal (38,20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("article_places","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePriceListIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnName("fk_article")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultipleOrderQty")
                        .HasColumnName("is_multiply_order_qty")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinOrderQty")
                        .HasColumnName("min_order_qty")
                        .HasColumnType("decimal (38,20)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<int>("ScaleUnitQty")
                        .HasColumnName("scale_unit_qty")
                        .HasColumnType("int");

                    b.Property<int>("ScaleUnitType")
                        .HasColumnName("scale_unit_type")
                        .HasColumnType("int");

                    b.Property<int>("UnitOrder")
                        .HasColumnName("unit_order")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnName("valid_from")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validto")
                        .HasColumnName("valid_to")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_pricelist_in","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePriceListOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnName("fk_article")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultipleOrderQty")
                        .HasColumnName("is_multiply_order_qty")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinOrderQty")
                        .HasColumnName("min_order_qty")
                        .HasColumnType("decimal (38,20)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<long>("Priority")
                        .HasColumnName("priority")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReorderTime")
                        .HasColumnName("reordertime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScaleUnitQty")
                        .HasColumnName("scale_unit_qty")
                        .HasColumnType("int");

                    b.Property<int>("ScaleUnitType")
                        .HasColumnName("scale_unit_type")
                        .HasColumnType("int");

                    b.Property<int>("UnitOrder")
                        .HasColumnName("unit_order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("article_pricelist_out","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleRange", b =>
                {
                    b.Property<Guid>("ArticleRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Addition")
                        .HasColumnName("addition")
                        .HasColumnType("decimal (38,20)");

                    b.Property<Guid>("ArticleId")
                        .HasColumnName("fk_article")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnName("fk_pricelist_in")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnName("fk_pricelist_out")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Discount")
                        .HasColumnName("discount")
                        .HasColumnType("decimal (38,20)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetPrice")
                        .HasColumnName("netprice")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("decimal (38,20)");

                    b.HasKey("ArticleRangeId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("Id");

                    b.HasIndex("Id");

                    b.ToTable("article_range","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureType")
                        .IsRequired()
                        .HasColumnName("nature_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("article_type","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Artist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("ArtistId");

                    b.ToTable("Artists","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.CompanyType", b =>
                {
                    b.Property<Guid>("CompanyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)")
                        .HasMaxLength(1000);

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.HasKey("CompanyTypeId");

                    b.ToTable("CompanyCompanyType","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<int>("EconomicArea")
                        .HasColumnName("economic_area")
                        .HasColumnType("int");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Iso2cc")
                        .IsRequired()
                        .HasColumnName("iso_2cc")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Iso3cc")
                        .IsRequired()
                        .HasColumnName("iso_3cc")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("IsoNumerical")
                        .HasColumnName("iso_numerical")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Type")
                        .HasColumnName("address_type")
                        .HasColumnType("int");

                    b.HasKey("CountryId");

                    b.ToTable("CompanyCountry","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyTextDelivery")
                        .HasColumnName("address_text_delivery")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CompanyTextDocument")
                        .HasColumnName("address_text_document")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CompanyTextInvoice")
                        .HasColumnName("address_text_invoice")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("DeliveryCompanyId")
                        .HasColumnName("fk_delivery_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeliveryPersonId")
                        .HasColumnName("fk_delivery_person")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentCompanyId")
                        .HasColumnName("fk_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentPersonId")
                        .HasColumnName("fk_person")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnName("type")
                        .HasColumnType("int");

                    b.Property<Guid?>("InvoiceCompanyId")
                        .HasColumnName("fk_invoice_address")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvoicePersonId")
                        .HasColumnName("fk_invoice_person")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsArchived")
                        .HasColumnName("is_archive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NetPriceSum")
                        .HasColumnName("price_sum_net")
                        .HasColumnType("decimal (38,20)");

                    b.Property<string>("Number")
                        .HasColumnName("number")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("PriceGross")
                        .HasColumnName("price_gross")
                        .HasColumnType("decimal (38,20)");

                    b.Property<int>("PrintCount")
                        .HasColumnName("print_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrintDate")
                        .HasColumnName("print_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReminderDate")
                        .HasColumnName("reminder_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<int>("SubType")
                        .HasColumnName("sub_type")
                        .HasColumnType("int");

                    b.Property<string>("TextDelivery")
                        .HasColumnName("text_delivery")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextDeliveryRTF")
                        .HasColumnName("text_delivery_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextEnd")
                        .HasColumnName("text_end")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextEndRTF")
                        .HasColumnName("text_end_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextHead")
                        .HasColumnName("text_head")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextHeadRTF")
                        .HasColumnName("text_head_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextPaymentTerms")
                        .HasColumnName("text_paymentterms")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextPaymentTermsRTF")
                        .HasColumnName("text_paymentterms_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextStart")
                        .HasColumnName("text_start")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TextStartRTF")
                        .HasColumnName("text_start_rtf")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TypeName")
                        .HasColumnName("type_name")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ValueBias")
                        .HasColumnName("value_basis")
                        .HasColumnType("int");

                    b.Property<Guid?>("fk_invoice_address")
                        .HasColumnName("fk_invoice_address1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DocumentId");

                    b.HasIndex("DeliveryCompanyId");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("DocumentCompanyId");

                    b.HasIndex("DocumentPersonId");

                    b.HasIndex("InvoicePersonId");

                    b.HasIndex("fk_invoice_address");

                    b.ToTable("document","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.DocumentPosition", b =>
                {
                    b.Property<Guid>("DocumentPositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnName("fk_article")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleNameExtern")
                        .HasColumnName("article_name_extern")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeliveryQty")
                        .HasColumnName("delivered_quantity")
                        .HasColumnType("decimal (38,20)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnName("fk_document")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPartialDelivered")
                        .HasColumnName("is_partial_delivery")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ParentId")
                        .HasColumnName("fk_parent")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionNumberText")
                        .IsRequired()
                        .HasColumnName("position_number_text")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("PositionType")
                        .HasColumnName("position_type")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceBase")
                        .HasColumnName("price_base")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnName("price_per_unit")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnName("price_total")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("Quantity")
                        .HasColumnName("quantitiy")
                        .HasColumnType("decimal (38,20)");

                    b.Property<decimal>("SalesTaxPercent")
                        .HasColumnName("sales_tax_percent")
                        .HasColumnType("decimal (38,20)");

                    b.Property<string>("ScaleUnit")
                        .HasColumnName("scale_unit")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ScaleUnitQty")
                        .HasColumnName("scale_unit_qty")
                        .HasColumnType("int");

                    b.Property<int>("ScaleUnitType")
                        .HasColumnName("scale_unit_type")
                        .HasColumnType("int");

                    b.HasKey("DocumentPositionId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ParentId");

                    b.ToTable("document_position","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.FAGBinary", b =>
                {
                    b.Property<Guid>("FAGBinaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Data")
                        .HasColumnName("data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .HasColumnName("file_name")
                        .HasColumnType("varchar(max)");

                    b.HasKey("FAGBinaryId");

                    b.HasIndex("ArticleId");

                    b.ToTable("fag_binary","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.FAGText", b =>
                {
                    b.Property<Guid>("FAGTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyPersonRelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleInventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleRangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DocumentPositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Iso2cc")
                        .HasColumnName("language_iso_2cc")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Iso3cc")
                        .HasColumnName("language_iso_3cc")
                        .HasColumnType("varchar(3)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnName("text")
                        .HasColumnType("varchar(max)");

                    b.Property<byte[]>("TextRTF")
                        .HasColumnName("text_rtf")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("FAGTextId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyPersonRelationId");

                    b.HasIndex("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleInventoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ArticleRangeId");

                    b.HasIndex("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentPositionId");

                    b.HasIndex("PersonId");

                    b.ToTable("fag_text","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("GenreId");

                    b.ToTable("Genres","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("LabelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReleaseDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.ToTable("Items","erp");
                });

            modelBuilder.Entity("ERP.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .HasColumnName("department")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstname")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnName("lastname")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("datetime2");

                    b.Property<long>("ModifiedBy")
                        .HasColumnName("modified_by")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneOffice")
                        .HasColumnName("phone_office")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhonePrivate")
                        .HasColumnName("phone_private")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("PictureId")
                        .HasColumnName("fk_picture")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sex")
                        .HasColumnName("sex")
                        .HasColumnType("varchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("PictureId");

                    b.ToTable("address_person");
                });

            modelBuilder.Entity("ERP.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ERP.Domain.Models.Company", b =>
                {
                    b.HasOne("ERP.Domain.Models.CompanyType", "CompanyType")
                        .WithMany("Companyes")
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Country", "Country")
                        .WithMany("Adresss")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.FAGBinary", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId");

                    b.HasOne("ERP.Domain.Models.Company", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("ERP.Domain.Models.CompanyPersonRelation", b =>
                {
                    b.HasOne("ERP.Domain.Models.Company", "Company")
                        .WithMany("CompanyPersonRelations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Person", "CompanyPerson")
                        .WithMany("CompanyPersonRelations")
                        .HasForeignKey("CompanyPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.Article", b =>
                {
                    b.HasOne("ERP.Domain.Models.ArticleGroup", "ArticleGroup")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleInventory", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", "Article")
                        .WithMany("ArticleInventories")
                        .HasForeignKey("ArticleInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.ArticlePlace", "ArticlePlace")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePlace", b =>
                {
                    b.HasOne("ERP.Domain.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePriceListIn", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticlePriceListOut", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.ArticleRange", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", "Article")
                        .WithMany("ArticleRanges")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.ArticlePriceListIn", "ArticlePriceListIn")
                        .WithMany("ArticleRanges")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.ArticlePriceListOut", "ArticlePriceListOut")
                        .WithMany("ArticleRanges")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.Document", b =>
                {
                    b.HasOne("ERP.Domain.Models.Company", "DeliveryCompany")
                        .WithMany()
                        .HasForeignKey("DeliveryCompanyId");

                    b.HasOne("ERP.Domain.Models.Person", "DeliveryPerson")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId");

                    b.HasOne("ERP.Domain.Models.Company", "DocumentCompany")
                        .WithMany()
                        .HasForeignKey("DocumentCompanyId");

                    b.HasOne("ERP.Domain.Models.Person", "DocumentPerson")
                        .WithMany()
                        .HasForeignKey("DocumentPersonId");

                    b.HasOne("ERP.Domain.Models.Person", "InvoicePerson")
                        .WithMany()
                        .HasForeignKey("InvoicePersonId");

                    b.HasOne("ERP.Domain.Models.Company", "InvoiceCompany")
                        .WithMany()
                        .HasForeignKey("fk_invoice_address");
                });

            modelBuilder.Entity("ERP.Domain.Models.DocumentPosition", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.DocumentPosition", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("ERP.Domain.Models.FAGBinary", b =>
                {
                    b.HasOne("ERP.Domain.Models.Article", null)
                        .WithMany("Pictures")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("ERP.Domain.Models.FAGText", b =>
                {
                    b.HasOne("ERP.Domain.Models.Company", null)
                        .WithMany("Infos")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ERP.Domain.Models.CompanyPersonRelation", null)
                        .WithMany("Infos")
                        .HasForeignKey("CompanyPersonRelationId");

                    b.HasOne("ERP.Domain.Models.ArticleGroup", null)
                        .WithMany("Infos")
                        .HasForeignKey("Id");

                    b.HasOne("ERP.Domain.Models.Article", null)
                        .WithMany("Infos")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ERP.Domain.Models.ArticleInventory", null)
                        .WithMany("Infos")
                        .HasForeignKey("ArticleInventoryId");

                    b.HasOne("ERP.Domain.Models.ArticlePlace", null)
                        .WithMany("Infos")
                        .HasForeignKey("Id");

                    b.HasOne("ERP.Domain.Models.ArticlePriceListIn", null)
                        .WithMany("Infos")
                        .HasForeignKey("Id");

                    b.HasOne("ERP.Domain.Models.ArticlePriceListOut", null)
                        .WithMany("Infos")
                        .HasForeignKey("Id");

                    b.HasOne("ERP.Domain.Models.ArticleRange", null)
                        .WithMany("Infos")
                        .HasForeignKey("ArticleRangeId");

                    b.HasOne("ERP.Domain.Models.ArticleType", null)
                        .WithMany("Infos")
                        .HasForeignKey("Id");

                    b.HasOne("ERP.Domain.Models.CompanyType", null)
                        .WithMany("Infos")
                        .HasForeignKey("CompanyTypeId");

                    b.HasOne("ERP.Domain.Models.Country", null)
                        .WithMany("Infos")
                        .HasForeignKey("CountryId");

                    b.HasOne("ERP.Domain.Models.Document", null)
                        .WithMany("Infos")
                        .HasForeignKey("DocumentId");

                    b.HasOne("ERP.Domain.Models.DocumentPosition", null)
                        .WithMany("Infos")
                        .HasForeignKey("DocumentPositionId");

                    b.HasOne("ERP.Domain.Models.Person", null)
                        .WithMany("Infos")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("ERP.Domain.Models.Item", b =>
                {
                    b.HasOne("ERP.Domain.Models.Artist", "Artist")
                        .WithMany("Items")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.Genre", "Genre")
                        .WithMany("Items")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP.Domain.Models.Person", b =>
                {
                    b.HasOne("ERP.Domain.Models.FAGBinary", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ERP.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
